[package]
name = "bb8-redis"
version = "0.1.0"
authors = ["Daniel Smith <smith.daniel.br@gmail.com>", "Kyle Huey <khuey@kylehuey.com>"]

[dependencies]
bb8 = { path = ".." }
futures = "0.1"
tokio-core = "0.1"
redis = "0.9"
